/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
 exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('receiver').del()
  await knex('receiver').insert([
    {id: 1, server_id: 1, team_id: 1, unit: 1, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 2, server_id: 1, team_id: 1, unit: 1, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 3, server_id: 1, team_id: 1, unit: 1, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 4, server_id: 1, team_id: 1, unit: 1, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 5, server_id: 1, team_id: 1, unit: 2, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 6, server_id: 1, team_id: 1, unit: 2, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 7, server_id: 1, team_id: 1, unit: 2, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 8, server_id: 1, team_id: 1, unit: 2, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 9, server_id: 1, team_id: 1, unit: 3, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 10, server_id: 1, team_id: 1, unit: 3, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 11, server_id: 1, team_id: 1, unit: 3, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 12, server_id: 1, team_id: 1, unit: 3, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 13, server_id: 1, team_id: 1, unit: 4, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 14, server_id: 1, team_id: 1, unit: 4, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 15, server_id: 1, team_id: 1, unit: 4, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 16, server_id: 1, team_id: 1, unit: 4, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 17, server_id: 1, team_id: 2, unit: 1, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 18, server_id: 1, team_id: 2, unit: 1, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 19, server_id: 1, team_id: 2, unit: 1, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 20, server_id: 1, team_id: 2, unit: 1, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 21, server_id: 1, team_id: 2, unit: 2, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 22, server_id: 1, team_id: 2, unit: 2, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 23, server_id: 1, team_id: 2, unit: 2, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 24, server_id: 1, team_id: 2, unit: 2, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 25, server_id: 1, team_id: 2, unit: 3, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 26, server_id: 1, team_id: 2, unit: 3, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 27, server_id: 1, team_id: 2, unit: 3, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 28, server_id: 1, team_id: 2, unit: 3, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 29, server_id: 1, team_id: 2, unit: 4, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 30, server_id: 1, team_id: 2, unit: 4, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 31, server_id: 1, team_id: 2, unit: 4, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 32, server_id: 1, team_id: 2, unit: 4, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 33, server_id: 1, team_id: 3, unit: 1, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 34, server_id: 1, team_id: 3, unit: 1, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 35, server_id: 1, team_id: 3, unit: 1, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 36, server_id: 1, team_id: 3, unit: 1, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 37, server_id: 1, team_id: 3, unit: 2, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 38, server_id: 1, team_id: 3, unit: 2, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 39, server_id: 1, team_id: 3, unit: 2, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 40, server_id: 1, team_id: 3, unit: 2, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 41, server_id: 1, team_id: 3, unit: 3, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 42, server_id: 1, team_id: 3, unit: 3, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 43, server_id: 1, team_id: 3, unit: 3, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 44, server_id: 1, team_id: 3, unit: 3, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 45, server_id: 1, team_id: 3, unit: 4, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 46, server_id: 1, team_id: 3, unit: 4, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 47, server_id: 1, team_id: 3, unit: 4, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 48, server_id: 1, team_id: 3, unit: 4, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 49, server_id: 1, team_id: 4, unit: 1, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 50, server_id: 1, team_id: 4, unit: 1, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 51, server_id: 1, team_id: 4, unit: 1, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 52, server_id: 1, team_id: 4, unit: 1, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 53, server_id: 1, team_id: 4, unit: 2, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 54, server_id: 1, team_id: 4, unit: 2, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 55, server_id: 1, team_id: 4, unit: 2, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 56, server_id: 1, team_id: 4, unit: 2, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 57, server_id: 1, team_id: 4, unit: 3, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 58, server_id: 1, team_id: 4, unit: 3, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 59, server_id: 1, team_id: 4, unit: 3, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 60, server_id: 1, team_id: 4, unit: 3, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 61, server_id: 1, team_id: 4, unit: 4, number: 1, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 62, server_id: 1, team_id: 4, unit: 4, number: 2, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 63, server_id: 1, team_id: 4, unit: 4, number: 3, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'},
    {id: 64, server_id: 1, team_id: 4, unit: 4, number: 4, operational: true, antenna_id: 1, freqency: 1250, bandwidth: 10, modulation: 'BPSK', fec: '1/2'}
  ]);
  await knex.raw('SELECT SETVAL(pg_get_serial_sequency(\'receiver\',\'id\'), (SELECT MAX(id) FROM receiver) )');
};
