export const defaultTxData = [
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 1,
    modem_number: 1,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 1,
    modem_number: 2,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 1,
    modem_number: 3,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 1,
    modem_number: 4,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 2,
    modem_number: 1,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 2,
    modem_number: 2,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 2,
    modem_number: 3,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 2,
    modem_number: 4,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 3,
    modem_number: 1,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 3,
    modem_number: 2,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 3,
    modem_number: 3,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 3,
    modem_number: 4,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 4,
    modem_number: 1,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 4,
    modem_number: 2,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 4,
    modem_number: 3,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
  {
    id: 1,
    server_id: 1,
    team_id: 1,
    unit: 4,
    modem_number: 4,
    operational: true,
    antenna_id: 1,
    frequency: 1000,
    bandwidth: 10,
    power: -70,
    transmitting: false,
  },
];
